export const problemSet: { [key: number]: string } = {
  1: "n \\times 11",
  2: "n \\times 25",
  3: "\\frac{n}{101}",
  4: "\\frac{n}{111}",
  5: "n  \\%  x",
  6: "n - x",
  7: "n + x",
  8: "NN \\times XX",
  9: "\\text{SQUARES}",
  10: "\\text{Tens Trick}",
  11: "\\Sigma : \\frac{n(n+1)}{2}",
  12: "\\text{Estimation}",
  13: "<100 \\text{ Multiplication}",
  14: ">100 \\text{ Multiplication}",
  15: "\\pm< 100 \\text{ Multiplication}",
  16: "\\text{Dec/Frac Conversion}",
  17: "\\text{Dec Addition/Subtraction}",
  18: "\\text{Roman Numerals}",
  19: "\\text{Cubes}",
  20: "\\text{GCD}",
  30: "\\text{LCM}",
  31: "\\text{Conversion into Base 10}",
  32: "\\text{Conversion from Base 10}",
  33: "\\text{Conversion of Base 2, 4, 8}",
  34: "\\text{Sum of Integral Divisors}",
  35: "\\text{Sum of Prime Divisors}",
  36: "\\frac{x}{90}, \\frac{x}{99}, \\frac{x}{900}, \\frac{x}{990}",
  37: "\\text{Triangular Numbers}",
  38: "\\text{Pentagonal Numbers}",
  39: "\\text{Hexagonal Numbers}",
  40: "x^2 + (2x)^2",
  41: "x^2 + (3x)^2",
  42: "\\text{Complex Number Multiplication}",
  43: "\\text{Unit Conversions}",
  44: "x^2 + (x+1)^2",
  45: "\\frac{a}{b} + \\frac{b}{a}",
  46: "\\# \\text{ of distinct diagonals in a polygon}",
  47: "\\text{Sum of } n \\text{ Squares}",
  48: "\\text{Alternating Sum of } n \\text{ Squares}",
  49: "\\text{Mean/Median}",
  50: "\\text{Geometric Mean}",
  51: "\\text{Harmonic Mean}",
  52: "\\text{Estimating Square/Cube Roots}",
  53: "\\frac{x}{100} \\text{ of } y",
  54: "\\frac{a \\times b}{c}",
  55: "(a+b) \\times (a-b)",
  56: "\\text{Fibonacci Series}",
  57: "\\text{Special Sum of Squares}",
  58: "\\text{3-digit Squares}",
  59: "\\text{3-digit Cubes}",
  60: "\\frac{x^3-y^3}{x-y}",
};

export const problemFunction: { [key: string]: Function } = {
  "1": n11,
};

function n11() {
  let num = Math.floor(Math.random() * (999 - 15 + 1)) + 15;
  return {
    body: "" + num + " * 11",
    ans: "" + num * 11,
  };
}
